#ifndef TRUNK_COMMONQRSHOW_H
#define TRUNK_COMMONQRSHOW_H

#include "minigui_comm.h"

#define COMMON_QR_STYLE_BIT(n)          (1UL << (n))

#define COMMON_QR_STYLE_FULL            COMMON_QR_STYLE_BIT(0)
#define COMMON_QR_STYLE_NAVBAR          COMMON_QR_STYLE_BIT(1)
#define COMMON_QR_STYLE_UPDOWN_KEY      COMMON_QR_STYLE_BIT(2)
#define COMMON_QR_STYLE_FONT12          COMMON_QR_STYLE_BIT(3)
#define COMMON_QR_STYLE_RIGHT_LEGACY    COMMON_QR_STYLE_BIT(4)
#define COMMON_QR_STYLE_RIGHT_SEGWIT    COMMON_QR_STYLE_BIT(5)
#define COMMON_QR_STYLE_RIGHT_CASH      COMMON_QR_STYLE_BIT(6)
#define COMMON_QR_STYLE_BUTTON          COMMON_QR_STYLE_BIT(7)
#define COMMON_QR_STYLE_RIGHT_NSEGWIT   COMMON_QR_STYLE_BIT(8)
#define COMMON_QR_STYLE_RIGHT_DEFAULT   COMMON_QR_STYLE_BIT(9)
#define COMMON_QR_STYLE_RIGHT_OPTIONAL  COMMON_QR_STYLE_BIT(10)
#define COMMON_QR_STYLE_RIGHT_TAPROOT   COMMON_QR_STYLE_BIT(11)
#define COMMON_QR_STYLE_RIGHT_SINGLE    COMMON_QR_STYLE_BIT(12)
#define COMMON_QR_STYLE_NAVBAR_NO_BAR   COMMON_QR_STYLE_BIT(13)
#define COMMON_QR_STYLE_RIGHT_LEGACY_LTC    COMMON_QR_STYLE_BIT(14)
#define COMMON_QR_STYLE_RIGHT_NSEGWIT_LTC   COMMON_QR_STYLE_BIT(15)
#define COMMON_QR_STYLE_RIGHT_LEGACY_BCH    COMMON_QR_STYLE_BIT(16)

#ifdef __cplusplus
extern "C" {
#endif
int showCommonQR(HWND parent, const unsigned char *data, int size, const char *msg, int style);
#ifdef __cplusplus
}
#endif
#endif
