#ifndef WALLET_EVENTS_H
#define WALLET_EVENTS_H

enum {
	CALLBACK_MSG_BEGIN = 300,
	CALLBACK_MSG_SHUTDOWN,
	CALLBACK_MSG_CAMERA_PREVIEW_STATE,
	CALLBACK_MSG_REFRESH_BATTERY,
	CALLBACK_MSG_LONG_KEYDOWN,
	CALLBACK_MSG_QUICK_SHORT_KEY,
	CALLBACK_MSG_FACT_AUTO_TEST,
};

enum {
	EVENT_USB_CONNECT = 1,
	EVENT_USB_DISCONNECT,
	EVENT_BATTERY_CHANGE,
	EVENT_BATTERY_ONLINE,
	EVENT_BATTERY_OFFLINE,
	EVENT_BATTERY_LOW,
};

#endif
