#ifndef WALLET_WIN_COMM_H
#define WALLET_WIN_COMM_H

#include <pthread.h>
#include <semaphore.h>
#include "platform.h"
#include "minigui_comm.h"

/* Window ID*/
enum {
	WINDOWID_MAIN = 0,
	WINDOWID_MAINPANEL,
	WINDOWID_SCAN,
	WINDOWID_QRPROC,
	WINDOWID_TXSHOW,
	WINDOWID_TXMORE,
	WINDOWID_SETTING,
	WINDOWID_GUIDE,
	WINDOWID_COINS_MANAGER,
	WINDOWID_COIN_DETAIL,
	WINDOWID_SIGN_HISTORY,
	WINDOWID_FACTORY,
	WINDOWID_ABOUT,
	WINDOWID_OTAOK,
	WINDOWID_PASSPHRASE,
	WINDOWID_VERIFY,
	WINDOWID_TX_VERIFY_CODE,
	WINDOWID_MAXID,
};

enum {
	MSG_RM_MSG_BASE = MSG_USER,
	MSG_RM_LANG_CHANGED,
	MSG_BATTERY_CHANGED,
	MSG_BATTERY_CHARGING,
	MLM_FLUSH_MENU_LIST,
	STBM_TIME_CLICK,
	MSG_QR_RESULT,
	MSG_QR_CHUNK,
	MSG_QR_ERROR,
	MSG_HISTORY_QR_RESULT,
	MSG_CHANGE_WIN_FROM,
	MSG_DISABLE_QRSCAN_WIN,
	MSG_SET_COIN_INFO,
	MSG_CHANGE_WINDOW,
	MSG_DESTORY_WINDOW,
	MSG_QUICK_SHORT_KEY,
	MSG_SECHIP_INITED,
	MSG_FACT_AUTO_TEST,
	MSG_TXMORE_TXP_MSG,
	MSG_TXSHOW_MSG,
};

enum {
	MSG_FROM_QR_APP = 0,
	MSG_FROM_QR_HISTORY,
};

#endif
