#ifndef MINIGUI_INCLUDE_GUICALLBACK_H_
#define MINIGUI_INCLUDE_GUICALLBACK_H_

#define CMD_MIN_VAL 0xA000
#define CMD_MAX_VAL 0xBB00

enum {

	CTRL_CMD_SET_LANGUAGE = 0xA013,//0xA013
	CTRL_CMD_SET_LANGUAGE_RESP,//0xA014

	CTRL_CMD_SCREEN_SLEEP = 0xA021, //
	CTRL_CMD_SCREEN_SLEEP_RESP, //

	CTRL_CMD_FACTORY_RESET = 0xA054, //0xA054
	CTRL_CMD_FACTORY_RESET_RESP,//0xA055

	CTRL_CMD_REBOOT_DEVICE = 0xA080, //0xA080
	CTRL_CMD_REBOOT_DEVICE_RESP, //0xA081

	CTRL_CMD_SHUTDOWNT_DEVICE = 0xA08A, //0xA08A
	CTRL_CMD_SHUTDOWNT_DEVICE_RESP, //0xA08B

	CTRL_CMD_SET_DEVICE_TIME = 0xA0B8,     //0xA0B8  req: 2int: time,timezone
	CTRL_CMD_SET_DEVICE_TIME_RESP,

	CTRL_CMD_SET_AUTO_SHOTDOWN_TIME = 0xB00B,
	CTRL_CMD_SET_AUTO_SHOTDOWN_TIME_RESP = 0xB00C,

	CTRL_CMD_SET_BRIGHTNESS = 0xB00D,
	CTRL_CMD_SET_BRIGHTNESS_RESP = 0xB00E,

    CTRL_CMD_SET_RAND_PIN_KEYPAD = 0xB00F,
    CTRL_CMD_SET_RAND_PIN_KEYPAD_RESP = 0xB010,

    CTRL_CMD_SET_BTC_MULTI_ADDRESS = 0xB011,
    CTRL_CMD_SET_BTC_MULTI_ADDRESS_RESP,
};

enum UI_CALLBACK_EVENT {
	UI_EVENT_APPMAIN_INITED = 0,
	UI_EVENT_MAP_NETCMD_START = 0,
	UI_EVENT_SET_SCREEN_SAVER,
	UI_EVENT_SET_LANG,
	UI_EVENT_SHUTDOWN,
	UI_EVENT_SET_BRIGHTNESS,
    UI_EVENT_SET_RAND_PIN_KEYPAD,
    UI_EVENT_SET_BTC_MULTI_ADDRESS,
	UI_EVENT_MAP_NETCMD_END,

	UI_EVENT_LOSE_POWER,
	UI_EVENT_BATTERY_CHANGE,
	UI_EVENT_BATTERY_CHARGING,
	UI_EVENT_QR_RESULT,
	UI_EVENT_QR_CHUNK,
	UI_EVENT_QR_ERROR,
	UI_EVENT_SEED_CHANGED,
	UI_EVENT_SECHIP_INITED,
	UI_EVENT_LONG_KEYDOWN,
	UI_EVENT_QUICK_SHORT_KEY,
	UI_EVENT_SCREEN_STATE,
	UI_EVENT_FACT_AUTO_TEST,
};

int UI_EVENT_TO_NET_CMD(int event);

int CMD_TO_UI_EVENT(int cmd);

class GuiCallBack {
public:
	GuiCallBack() {}

	virtual ~GuiCallBack() {}

	virtual int onUiEvent(int event, int param, long param2) = 0;

};

#endif /* MINIGUI_INCLUDE_GUICALLBACK_H_ */
